### ISSUE TITLE
eprosima::fastcdr::exception::BadParamException Unexpected non-zero initial byte received in Cdr::read_encapsulation

### ISSUE THREAD

**Issue by minami9** [eProsima/Fast-CDR#111]
## test case
the idl file show you below:
```
struct LatencyMeasureMessage {
      @key char data[65536];
};

struct LatencyMeasureEcho {
      @key char data[65536];
};
```
there have two Participant that it both have a publisher and subscriber,like this:

![image](https://user-images.githubusercontent.com/14040726/125571416-11e53438-3e61-45f5-9d12-63efe498d501.png)

A and B running on a different machine， but on the same LAN.

The test detail is follow link: 
https://www.eprosima.com/index.php/resources-all/performance/fast-dds-vs-cyclone-dds-performance

First exec B side and then exec A side，there is no problem when the data size is equal to 16384，but the issue as title is  occurred when the data size is equal to 65536.
```
terminate called after throwing an instance of 'eprosima::fastcdr::exception::BadParamException'
  what():  Unexpected non-zero initial byte received in Cdr::read_encapsulation
Aborted (core dumped)

```

# test environment
Linux  4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubunut 18.04

**Comment by MiguelCompany** [comment]
@minami9 Would you mind telling the versions of Fast CDR and Fast DDS being used?

**Comment by QinChen686** [comment]
I also met this problem with the FastDDS version 2.3.4 and Fast CDR version 1.0.22, in linux arm64 platform. Could you please give some suggestions?

> @minami9 Would you mind telling the versions of Fast CDR and Fast DDS being used?

**Comment by richiware** [comment]
In your case of large data the samples are been fragmented and your problem may be related with eProsima/Fast-DDS#2239. Could you test against that branch?

**Comment by QinChen686** [comment]
> In your case of large data the samples are been fragmented and your problem may be related with [eProsima/Fast-DDS#2239](https://github.com/eProsima/Fast-DDS/pull/2239). Could you test against that branch?

Thanks a lot, it works!
