### ISSUE TITLE
(De)serialization of std::chrono::system_clock::time_point [13752]

### ISSUE THREAD

**Issue by lhruby** [eProsima/Fast-CDR#116]
While custom classes can be easily serialized by overloads of `(de)serialize` or `operator<<` and `operator>>`, this is tricky in the case of data types from the standard library. In this instance, we want to serialize `std::chrono::system_clock::time_point`.

Note: The following is true for `serialization` and `operator<<` in the same way.
Overloading `operator>>` leads to an incorrect template parsing if used in a custom namespace, thus FastCdr falls back to the default 
```
template<class _T>
inline FastCdr& operator >>(std::vector<_T>& vector_t)
{
    return deserialize<_T>(vector_t);
}
```
Since `deserialize` is not implemented in `std::chrono::system_clock::time_point`, this does not work, and the compiler throws an error.

One solution is to call (de)serialize directly with the correct namespace. Another solution would be to extend FastCdr.h for `std::chrono::system_clock::time_point`. 

Here is a code suggestion for

```
inline void serialize(const std::chrono::system_clock::time_point& timestamp, serdes::SerDes& ser) {
  ser << static_cast<uint64_t>(
      std::chrono::duration_cast<std::chrono::nanoseconds>(timestamp.time_since_epoch()).count());
}

inline void deserialize(serdes::SerDes& ser, std::chrono::system_clock::time_point& timestamp) {
  uint64_t nanoseconds{};
  ser >> nanoseconds;
  const auto dur = std::chrono::duration_cast<std::chrono::system_clock::duration>(
      std::chrono::nanoseconds(nanoseconds));
  timestamp = std::chrono::system_clock::time_point(dur);
}
```
Using appropriate templates, `std::chrono::steady_clock` can probably be implemented the same way.

**Comment by MiguelCompany** [comment]
@lhruby Please have a look at #153, which will let you do something like the following:

```
namespace eprosima {
namespace fastcdr {

inline Cdr& operator << (Cdr& cdr, const std::chrono::system_clock::time_point& timestamp)
{
    cdr << static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::nanoseconds>(timestamp.time_since_epoch()).count());
    return cdr;
}

inline Cdr& operator >> (Cdr& cdr, std::chrono::system_clock::time_point& timestamp)
{
    uint64_t nanoseconds{};
    cdr >> nanoseconds;
    const auto dur = std::chrono::duration_cast<std::chrono::system_clock::duration>(
        std::chrono::nanoseconds(nanoseconds));
    timestamp = std::chrono::system_clock::time_point(dur);
    return cdr;
}

}  // namespace fastcdr
}  // namespace eprosima
```

Before the PR it was already possible, but the PR will allow to also use `std::array` and `std:vector` collections of timepoints.

**Comment by MiguelCompany** [comment]
I will go ahead and close this, since #153 provides the mechanism for the user to solve the issue.
