### ISSUE TITLE
Where is the package.xml?

### ISSUE THREAD

**Issue by xander-m2k** [eProsima/Fast-CDR#119]
I want to binary build this package to ros-foxy-fastcdr, but I cannot seem to find a package.xml

**Comment by xander-m2k** [comment]
I have made a simple one myself, which does the job:
```
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fastcdr</name>
  <version>1.0.23</version>
  <description>
     Fast-CDR
  </description>
  <maintainer email="miguelcompany@eprosima.com">Miguel Company</maintainer>
  <maintainer email="eduardoponz@eprosima.com">Eduardo Ponz</maintainer>
  <license file="LICENSE">Apache 2.0</license>

  <url type="website">https://www.eprosima.com/</url>
  <url type="bugtracker">https://github.com/eProsima/Fast-CDR/issues</url>
  <url type="repository">https://github.com/eProsima/Fast-CDR</url>

  <buildtool_depend>cmake</buildtool_depend>

  <doc_depend>doxygen</doc_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>


```

**Comment by MiguelCompany** [comment]
@xander-m2k The one used for the official ROS 2 distributions lies [here](https://github.com/ros2-gbp/fastcdr-release/blob/master/foxy/package.xml).

**Comment by xander-m2k** [comment]
@MiguelCompany Wow, I have never seen these repositories by 'ros2-gpb'. It keeps suprising me how insanely weird and complex the whole build structure of ROS2 is. It's based on hundreds of little extra repositories which serve their part for another repository. Most of the things are pretty unfindable on Google.

I'm currently working on a docker script which fully builds all binaries of the ROS Foxy distro. Just used vcs (as documented on the ROS Foxy website) to import all repo's, and this repo also gets pulled, so I did not get the package.xml. Thanks anyway!
