### ISSUE TITLE
Long double datatype aligned on wrong boundary

### ISSUE THREAD

**Issue by tparys** [eProsima/Fast-CDR#12]
Size and alignment boundary for "long double" types differ in OMG CDR spec. Size is 16 bytes, but aligned on multiple of 8.

http://www.ciaranmchale.com/corba-explained-simply/on-the-wire-protocols.html

Looks like lines 524 and 1383 of CDR.cpp.

**Comment by richiware** [comment]
Commit aa8c785cadee6339d74f269b7e2f368757169e8f fixes it. Thanks for the reporting.

**Comment by JaimeMartin** [comment]
Hi @tparys , 

Thank you for the contribution. It would be very interesting to have a conversation about your use case, could you send me an email to jaimemartin@eprosima.com ?

**Comment by richiware** [comment]
I will close this issue. If you find any problem, you could reopen it. Thanks
