### ISSUE TITLE
terminate called after throwing an instance of 'eprosima::fastcdr::exception::BadParamException'   what():  Unexpected byte value in Cdr::deserialize(bool), expected 0 or 1 Aborted (core dumped)

### ISSUE THREAD

**Issue by Attahayat** [eProsima/Fast-CDR#130]
Problem:
I get the error in the title when I try to run micrortps_agent on RaspberryPi but I am able to transmit and receive messages (by using "micrortps_client status" command) when I use my PC. I followed the same procedure in both cases and both my PC and raspberry pi have identical configurations.

The procedure I followed in both cases:
Install ROS2 Foxy on ubuntu 20.04
Follow the installation guide (https://docs.px4.io/main/en/ros/ros2_comm.html#install-fast-dds) to set up PX4-ros2 bridge
Set up ethernet connection with client ip set to 192.168.0.4 and RaspberryPi/PC set to 192.168.0.1
Use mavlinkshell.py to start the client on PX4 with "micrortps_client start -t UDP -i 192.168.0.1"
Start micrortps_agent with "micrortps_agent start -t UDP -i 192.168.0.4"

I noticed that as soon as I start the client with Raspberry Pi, I get the error on agent's side. I tried reverting to older version of PX4-Autopilot but I am still facing this problem.

**Comment by pablogs9** [comment]
Hello @Attahayat,

I guess that you are using an old and unsupported product. Since `micrortps` is not supported anymore, have you considered moving to [Micro XRCE-DDS](https://micro-xrce-dds.docs.eprosima.com/en/latest/). 

In any case, if you  have any doubt please contact our support mail for more details: info@eProsima.com

**Comment by Attahayat** [comment]
> Hello @Attahayat,
> 
> I guess that you are using an old and unsupported product. Since `micrortps` is not supported anymore, have you considered moving to [Micro XRCE-DDS](https://micro-xrce-dds.docs.eprosima.com/en/latest/)?
> 
> In any case, if you have any doubts please contact our support mail for more details: [info@eProsima.com](mailto:info@eProsima.com)

Actually the problem turned out to be with the new version of px4_ros_com(https://github.com/PX4/px4_ros_com). I reverted back to the version which was working on my laptop and now it works fine on the pi as well.

I followed the instructions for px4-ros2 bridge here: https://docs.px4.io/main/en/ros/ros2_comm.html. Do you suppose the documentation is out of date?

**Comment by pablogs9** [comment]
@Attahayat I don't know the status of the PX4 documentation, but for sure microRTPS is not eProsima's supported product.
