### ISSUE TITLE
An exception was thrown but lacked capture and handling, resulting in rtps crash

### ISSUE THREAD

**Issue by Ashieta** [eProsima/Fast-CDR#144]
We found that an exception will be thrown at line 118 of /Fast-CDR/src/cpp/Cdr.cpp, but there is no subsequent processing of this exception. This caused a crash during a Fast-RTPS run.
The specific source code location is below:

/Fast-CDR/src/cpp/Cdr.cpp 
...
    catch (Exception& ex)
    {
        setState(state_before_error);
        ex.raise();
    }
...

/Fast-CDR/src/cpp/exceptions/NotEnoughMemoryException.cpp(Line 74):
...
 void NotEnoughMemoryException::raise() const
 {
       throw *this;
 }
...

**Comment by JLBuenoLopez-eProsima** [comment]
Fast DDS did not catch every Fast CDR exception as reported in this ticket. This was already solved in eProsima/Fast-DDS#3528. This PR was included in Fast DDS v2.11.0 release.
