### ISSUE TITLE
cpack destination directory not set correctly

### ISSUE THREAD

**Issue by rainerleuschke** [eProsima/Fast-CDR#146]
I am using the [fast dds cmake installation instructions](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html#global-installation) to build fast-cdr.
The instructions for global installation place libraries into `/usr/local`
When packaging the build with `cpack -G DEB` the destination directory is ignored and install root of the deb package becomes `/usr`.

Fix: add `set(CPACK_SET_DESTDIR "ON")` to CMakeLists.txt

**Comment by JLBuenoLopez-eProsima** [comment]
CPack has been removed from Fast CDR project since the latest release, v2.0.0.
