### ISSUE TITLE
FastBuffer::resize will not resize below 200

### ISSUE THREAD

**Issue by Karsten1987** [eProsima/Fast-CDR#15]
Connects to ros2/demos#185

I wonder why the implementation of `FastBuffer::resize` can't resize an empty buffer below 200. 
https://github.com/eProsima/Fast-CDR/blob/master/src/cpp/FastBuffer.cpp#L45-L81

If I have an empty buffer and want to resize it to an exact number of size - let's say I know how much data I want to copy into it - the minimum size of it is `BUFFER_START_LENGTH`, which is hard set to 200
https://github.com/eProsima/Fast-CDR/blob/master/src/cpp/FastBuffer.cpp#L23

why is that?

**Comment by richiware** [comment]
`FastBuffer` class can handle a user's buffer (`char*`) or an internal buffer. Usually I use the first approach. I know the length of my serialized data and I give a buffer to `FastBuffer`.

The second approach was useful if user doesn't know the length of the serialized data and doesn't want to precaculate it. We select to start with 200bytes. `Cdr`  starts serializing and when the internal buffer size is insufficient, it will reallocate more and continue serializing.

**Comment by Karsten1987** [comment]
I understand. However, this requires that the memory for the buffer is managed externally. That is to alloc and de-allocate the external buffer.
With the referenced `reserve` function, the buffer could stay internally and the destructor of the class can conveniently cleanup the allocated memory.

**Comment by Karsten1987** [comment]
closed by https://github.com/eProsima/Fast-CDR/commit/e986a9e4a2c96e3a8bcebaa72085f006d1e613ed
