### ISSUE TITLE
Failed to build using the latest version [19509]

### ISSUE THREAD

**Issue by TalonYhy** [eProsima/Fast-CDR#164]
When I use the latest version for building, the following warning will appear:

xxx@V-Ubuntu:~/MyWorkSpace/MyDDSProject/Fast-CDR/build$ cmake --build . --target install
[ 11%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/Cdr.cpp.o
/home/xxx/MyWorkSpace/MyDDSProject/Fast-CDR/src/cpp/Cdr.cpp: In member function ‘void eprosima::fastcdr::Cdr::xcdr1_serialize_short_member_header(const eprosima::fastcdr::MemberId&)’:
/home/xxx/MyWorkSpace/MyDDSProject/Fast-CDR/src/cpp/Cdr.cpp:2377:79: warning: conversion from ‘int’ to ‘uint16_t’ {aka ‘short unsigned int’} may change value [-Wconversion]
 2377 |     uint16_t flags_and_member_id = (member_id.must_understand ? 0x4000 : 0x0) | static_cast<uint16_t>(member_id.id);
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xxx/MyWorkSpace/MyDDSProject/Fast-CDR/src/cpp/Cdr.cpp: In member function ‘void eprosima::fastcdr::Cdr::xcdr1_change_to_short_member_header(const eprosima::fastcdr::MemberId&, size_t)’:
/home/xxx/MyWorkSpace/MyDDSProject/Fast-CDR/src/cpp/Cdr.cpp:2429:79: warning: conversion from ‘int’ to ‘uint16_t’ {aka ‘short unsigned int’} may change value [-Wconversion]
 2429 |     uint16_t flags_and_member_id = (member_id.must_understand ? 0x4000 : 0x0) |
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
 2430 |             static_cast<uint16_t>(member_id.id);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                
[ 22%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/CdrSizeCalculator.cpp.o
[ 33%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/FastCdr.cpp.o
[ 44%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/FastBuffer.cpp.o
[ 55%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/exceptions/BadOptionalAccessException.cpp.o
[ 66%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/exceptions/BadParamException.cpp.o
[ 77%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/exceptions/Exception.cpp.o
[ 88%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/exceptions/NotEnoughMemoryException.cpp.o
[100%] Linking CXX shared library libfastcdr.so
[100%] Built target fastcdr

Moreover, the following errors may also occur when building Fast-DDS

xxx@V-Ubuntu:~/MyWorkSpace/MyDDSProject/Fast-DDS/build$ cmake --build . --target install
[  0%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp.o
In file included from /home/xxx/MyWorkSpace/MyDDSProject/Fast-DDS/include/fastdds/dds/topic/IContentFilter.hpp:30,
                 from /home/xxx/MyWorkSpace/MyDDSProject/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.hpp:27,
                 from /home/xxx/MyWorkSpace/MyDDSProject/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:19:
/home/xxx/MyWorkSpace/MyDDSProject/Fast-DDS/include/fastrtps/types/TypesBase.h:273:27: error: expected unqualified-id before numeric constant
  273 | #define MEMBER_ID_INVALID 0X0FFFFFFF
      |                           ^~~~~~~~~~
In file included from /home/xxx/MyWorkSpace/MyDDSProject/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:31:
/home/xxx/MyWorkSpace/MyDDSProject/install/include/fastcdr/Cdr.h: In member function ‘eprosima::fastcdr::Cdr& eprosima::fastcdr::Cdr::operator<<(const _T&)’:
/home/xxx/MyWorkSpace/MyDDSProject/install/include/fastcdr/Cdr.h:327:31: error: no match for ‘operator==’ (operand types are ‘int’ and ‘eprosima::fastcdr::MemberId’)
  327 |         if (MEMBER_ID_INVALID == next_member_id_)
      |                               ^~ ~~~~~~~~~~~~~~~
      |                                  |
      |                                  eprosima::fastcdr::MemberId
/home/xxx/MyWorkSpace/MyDDSProject/install/include/fastcdr/Cdr.h: In member function ‘eprosima::fastcdr::Cdr& eprosima::fastcdr::Cdr::operator>>(_T&)’:
/home/xxx/MyWorkSpace/MyDDSProject/install/include/fastcdr/Cdr.h:357:31: error: no match for ‘operator==’ (operand types are ‘int’ and ‘eprosima::fastcdr::MemberId’)
  357 |         if (MEMBER_ID_INVALID == next_member_id_)
      |                               ^~ ~~~~~~~~~~~~~~~
      |                                  |
      |                                  eprosima::fastcdr::MemberId
/home/xxx/MyWorkSpace/MyDDSProject/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp: In member function ‘virtual bool eprosima::fastdds::dds::DDSSQLFilter::DDSFilterExpression::evaluate(const SerializedPayload&, const eprosima::fastdds::dds::IContentFilter::FilterSampleInfo&, const GUID_t&) const’:
/home/xxx/MyWorkSpace/MyDDSProject/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:60:95: error: ‘DDS_CDR’ is not a member of ‘eprosima::fastcdr::Cdr’
   60 |         Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN, eprosima::fastcdr::Cdr::DDS_CDR);
      |                                                                                               ^~~~~~~
make[2]: *** [src/cpp/CMakeFiles/fastrtps.dir/build.make:90：src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:941：src/cpp/CMakeFiles/fastrtps.dir/all] error 2
make: *** [Makefile:146：all] error 2

I have tried the old version (v1.0.28), it works!

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks for the report @TalonYhy 

Fast CDR has just recently broken API and consequently, any library using Fast CDR latest will probably not compile until it migrates to the new API. So you need to use some stable version of Fast CDR when building Fast DDS, until the migration is complete (eProsima/Fast-DDS#3828 has to be merged).

Regarding the warnings building Fast CDR, which compiler are you using? Thanks!

**Comment by TalonYhy** [comment]
OKOK, thanks a lot!
I used CMake.

**Comment by JLBuenoLopez-eProsima** [comment]
@TalonYhy 

CMake is a tool over the compiler properly speaking. I would like to know if you are using GCC, Clang or any other compiler and which version. We have tried to reproduce using GCC v11 and we have not been able to. Thanks for your help!

**Comment by TalonYhy** [comment]
Yes, I found the log: "The CXX compiler identification is GNU 9.4.0".
I just want to run the helloword program in Fast-DDS, but I meet something wrong in Fast-CDR.
I have run it successfully about one month ago, so I guess there is a version problem. So, I want to know which one is the stable version. Thanks!

**Comment by JLBuenoLopez-eProsima** [comment]
If you follow the instructions on [Fast DDS documentation](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html) you should be able to run the HelloWorld example. Right now we are in the process of upgrading to a major release in Fast CDR, so using master branch is risky. You can always use one of the stable branches as `2.10.x` which has the [dependencies fixed](https://github.com/eProsima/Fast-DDS/blob/2.10.x/fastrtps.repos) to a specific release.

**Comment by TalonYhy** [comment]
OK，I'll try it~

**Comment by TalonYhy** [comment]
It runs successfully!! You really helped me a lot，thx!!
