### ISSUE TITLE
installation destination of LICENSE on Windows

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-CDR#17]
Currently the `LICENSE` file is being installed into the `CMAKE_INSTALL_PREFIX` on Windows. That is a rather uncommon location. The file should be installed to a package specific location instead.

**Comment by richiware** [comment]
Currently i'm working on fastrtps and fastcdr CMakeLists.txt. I still have to test a lot with new changes but I will incorporate you suggestion.

**Comment by richiware** [comment]
Commit 7c53137e6a5c376c437157791bf51dfe6b422f33 solves this issue.

**Comment by MiguelCompany** [comment]
This was solved long ago. Closing issue
