### ISSUE TITLE
what's the different vs protobuf

### ISSUE THREAD

**Issue by stanal** [eProsima/Fast-CDR#174]
why not use protobuf directly?

**Comment by JLBuenoLopez-eProsima** [comment]
@stanal 

Fast CDR implements the Common Data Representation (CDR) defined by the OMG. The [README](https://github.com/eProsima/Fast-CDR) clearly describes the content of the repository. Surely, there are libraries implementing protobuf specification, but unfortunately, Fast CDR is not one of them.
