### ISSUE TITLE
v1.0.7 is not a "release" but the latest clone generates a libfastcdr.so.1.0.7 library

### ISSUE THREAD

**Issue by nrahnemoon** [eProsima/Fast-CDR#18]
I have a project in which I specify the version number along with the clone (via ansible).  Currently, under [releases](https://github.com/eProsima/Fast-CDR/releases), the repo only goes up to v1.0.6, but the latest clone actually corresponds to v1.0.7.

Could you please make a new release?

**Comment by nrahnemoon** [comment]
Thanks @richiware

**Comment by richiware** [comment]
Version 1.0.7 has been tagged. I close this issue. Thanks again
