### ISSUE TITLE
Cmake configure step fails with CMake 3.5

### ISSUE THREAD

**Issue by mikaelarguedas** [eProsima/Fast-CDR#20]
As of e591fdcc3f3b247eb740df27153f3f816584287b Fast-CDR doesn't pass the configuration step with CMake 3.5 anymore.
The issue seems to be that the project specifies the project as CXX but that the CMake tries to compile C code to perform the checks.

Cmake output with CMake 3.5 (failing):
https://ci.ros2.org/job/ci_linux/4594/console#console-section-5

Cmake output with CMake 3.10 (passing):
https://ci.ros2.org/job/ci_linux/4593/console#console-section-4

**Comment by richiware** [comment]
Sorry, I was working with last CMake version. Commit e1c127684fee72ebff88398acbcf096f710a7061 should solve it.

**Comment by mikaelarguedas** [comment]
closing as this has been fixed in https://github.com/eProsima/Fast-CDR/commit/e1c127684fee72ebff88398acbcf096f710a7061
