### ISSUE TITLE
master fails to build on Xenial 16.04

### ISSUE THREAD

**Issue by wjwwood** [eProsima/Fast-CDR#21]
Our nightly jobs that test Xenial are now failing after https://github.com/eProsima/Fast-CDR/commit/63202c16739dc527f8ba7456847bb8dcb7ddab5b (our main jobs based on Bionic pass):

```
10:30:41 -- Configuring done
10:30:41 CMake Error at cmake/common/check_configuration.cmake:119 (target_compile_options):
10:30:41   Error evaluating generator expression:
10:30:41 
10:30:41     $<VERSION_GREATER_EQUAL:$<CXX_COMPILER_VERSION>,6.0.0>
10:30:41 
10:30:41   Expression did not evaluate to a known generator expression
10:30:41 Call Stack (most recent call first):
10:30:41   src/cpp/CMakeLists.txt:51 (set_common_compile_options)
10:30:41 
10:30:41 
10:30:41 -- Generating done
10:30:41 -- Build files have been written to: /home/rosbuild/ci_scripts/ws/build/fastcdr
10:30:41 ---
10:30:41 
```

Looks like the `VERSION_GREATER_EQUAL` generator expression is not available in the cmake version distributed with Xenial (CMake `3.5.1-1ubuntu1`). Near as I can tell this feature was added in version `3.7` of CMake: https://cmake.org/cmake/help/v3.7/manual/cmake-generator-expressions.7.html

I'm not sure what an alternative would be, but perhaps this can be done without a generator expression.

**Comment by richiware** [comment]
Commit d998f853376bce42f15f10e565fca6d5e1839bdd should fix the error. Thanks for the reporting.
↪ 2018-07-27 vie 00:08, William Woodall <notifications@github.com>:

**Comment by wjwwood** [comment]
Thanks, we'll see tonight. I'll close it tomorrow if it's green!

**Comment by wjwwood** [comment]
Thanks @richiware it's passing again (warnings are unrelated to your changes):

https://ci.ros2.org/view/nightly/job/nightly_xenial_linux_release/52/
