### ISSUE TITLE
Unknown warning option on OSX

### ISSUE THREAD

**Issue by Karsten1987** [eProsima/Fast-CDR#22]
When compiling locally on my machine (`-DCMAKE_CXX_FLAGS=-Werror`), my clang compiler complains about two unsupported warnings:

```
error: : unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'?
```
```
error: : unknown warning option '-Wuseless-cast'
```

Both are found in here:
https://github.com/eProsima/Fast-CDR/blob/master/cmake/common/check_configuration.cmake#L129-L130

OSX: macOS Sierra, Version 10.12.6
CLANG: clang version 7.0.0 (https://llvm.org/git/clang.git 4f6bfc6f7dced31f46786058f1c8472d3b2b215a) (https://llvm.org/git/llvm.git d9367a91972e6631f831c329a47856785031d58e)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

**Comment by richiware** [comment]
Those warning options should be only supported by GNU GCC. Commit 1df42bbd1ea86a9c99bb8fa72104f19872235986 should solve 
your problem. Now we check whether compiler is GNU GCC or not.
↪ 2018-08-07 mar 19:08, Karsten Knese <notifications@github.com>:

**Comment by Karsten1987** [comment]
that seems to work. Thanks for the update.
