### ISSUE TITLE
deserialize´s method with error. (long double, BIG_ENDIANNESS)

### ISSUE THREAD

**Issue by joseAndresGomezTovar** [eProsima/Fast-CDR#25]
serialize use 16 bytes
`
            m_currentPosition++ << dst[15];
            m_currentPosition++ << dst[14];
            m_currentPosition++ << dst[13];
            m_currentPosition++ << dst[12];
            m_currentPosition++ << dst[11];
            m_currentPosition++ << dst[10];
            m_currentPosition++ << dst[9];
            m_currentPosition++ << dst[8];
            m_currentPosition++ << dst[7];
            m_currentPosition++ << dst[6];
            m_currentPosition++ << dst[5];
            m_currentPosition++ << dst[4];
            m_currentPosition++ << dst[3];
            m_currentPosition++ << dst[2];
            m_currentPosition++ << dst[1];
            m_currentPosition++ << dst[0];
`
however deserialize use only 8 bytes

`
            m_currentPosition++ >> dst[7];
            m_currentPosition++ >> dst[6];
            m_currentPosition++ >> dst[5];
            m_currentPosition++ >> dst[4];
            m_currentPosition++ >> dst[3];
            m_currentPosition++ >> dst[2];
            m_currentPosition++ >> dst[1];
            m_currentPosition++ >> dst[0];
`

to fixed the issue. adding this 
`
            m_currentPosition++ >> dst[15];
            m_currentPosition++ >> dst[14];
            m_currentPosition++ >> dst[13];
            m_currentPosition++ >> dst[12];
            m_currentPosition++ >> dst[11];
            m_currentPosition++ >> dst[10];
            m_currentPosition++ >> dst[9];
            m_currentPosition++ >> dst[8];
`

before of this

`
m_currentPosition++ >> dst[7];
`

**Comment by MiguelCompany** [comment]
This has been addressed as part of #23
