### ISSUE TITLE
serializeArray and deserializeArray(const int16_t *short_t, size_t numElements) and 

### ISSUE THREAD

**Issue by joseAndresGomezTovar** [eProsima/Fast-CDR#27]
All the serializeArray and deserializeArray methods with:
int16_t *short_t
int32_t *long_t
int64_t *longlong_t
float *float_t
double *double_t
long double *ldouble_t

with BIG ENDIANNESS as Endianness value, were developed incorrectly

this problem is solved by changing the cast
char *dst = reinterpret_cast<char*>(&

**Comment by MiguelCompany** [comment]
Hi @joseAndresGomezTovar,

Why did you close the PR? Could you reopen it and only include the changes related to this issue?

**Comment by LuisGP** [comment]
I'm closing this issue due to lack of feedback and the PR is probably obsolete.
@joseAndresGomezTovar Feel free to reopen it again if you think the implementation is still incorrect.
