### ISSUE TITLE
Undefined Behavior from Load of misaligned address

### ISSUE THREAD

**Issue by geoffviola** [eProsima/Fast-CDR#64]
When I run the unit tests with `-fsanitize=undefined` on clang 9.0.1, it reports `runtime error: load of misaligned address 0xXXXXXXXXXXXX for type 'blah', which requires x byte alignment`. The offending lines are
https://github.com/eProsima/Fast-CDR/blob/master/include/fastcdr/FastBuffer.h#L98
```
*(reinterpret_cast<_T*>(m_currentPosition)) = data;
```
and
https://github.com/eProsima/Fast-CDR/blob/master/include/fastcdr/FastBuffer.h#L116
```
data = *(reinterpret_cast<_T*>(m_currentPosition));
```

Is there a reason the `#if defined(FASTCDR_ARM32)` section isn't used in all cases?

**Comment by richiware** [comment]
Can you list the name of those tests, please? It will be useful.

**Comment by geoffviola** [comment]
If I run cmake with the following options
```
cmake -DCMAKE_BUILD_TYPE=Release -DEPROSIMA_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS=-fsanitize=undefined ..
```
And then run `test/UnitTests`

These tests report errors:
1. CDRTests.ZeroSequenceAtTheEnd
2. FastCDRTests.STDArrayString
3. FastCDRTests.Complete

There isn't a warning from `-Wcast-align`.

**Comment by MiguelCompany** [comment]
Closing via #67
