### ISSUE TITLE
Truncated length of std::string

### ISSUE THREAD

**Issue by mjopenglsdl** [eProsima/Fast-CDR#69]
I use **protobuf** to serialize some data into an **std::string**. the actual length is about 46, but aftering serializing the string with **Fast-CDR** the length becomes 19.
I have found that there was a byte with **'\0'** inside the **protobuf** serialized string, which has caused the size mismatch (because **Fast-CDR** uses **c_str()** of the string to find the length):
[https://github.com/eProsima/Fast-CDR/blob/84962690c0cd5d06c7a77fd9b51287c7c8f62060/include/fastcdr/Cdr.h#L962](https://github.com/eProsima/Fast-CDR/blob/84962690c0cd5d06c7a77fd9b51287c7c8f62060/include/fastcdr/Cdr.h#L962)
I think it is better to use the actual length of **std::string**, and I have provided a temporary solution:
[https://github.com/mjopenglsdl/Fast-CDR/commit/fef4d2f2a7d40b79a96cef66f3a67e823cafac3f](https://github.com/mjopenglsdl/Fast-CDR/commit/fef4d2f2a7d40b79a96cef66f3a67e823cafac3f)

There might be a better way to do it.

**Comment by LuisGP** [comment]
Hi @mjopenglsdl 

As you can see in the [CDR standard](https://www.omg.org/cgi-bin/doc?formal/02-06-51.pdf) (section 15.3.2.7)

> A string is encoded as an unsigned long indicating the length of the string in octets, followed by the string value in single- or multi-byte form represented as a sequence of octets. The string contents include a single terminating null character. The string length includes the null character, so an empty string has a length of 1.

*protobuf* may serialize the data into an `std::string`, but for CDR a string isn't a raw buffer of bytes.
Probably you should convert that string into a sequence of octets for this purpose, or an `std::vector`.

**Comment by mjopenglsdl** [comment]
I agree with you @LuisGP. 
ok let's follow the standard :+1:
