### ISSUE TITLE
DDS-XTypes 1.2 roadmap [13747]

### ISSUE THREAD

**Issue by pavelpgt** [eProsima/Fast-CDR#76]
I would like to ask you what is the state of DDS-XTypes 1.2 implementation.
I would like to communicate with RTI Implementation of DDS that uses @optional annotation within IDL.
You have stated in https://github.com/eProsima/Fast-DDS/issues/903 that serialization library (Fast-CDR) doesn't still support XCDR standard.
Support all DDS-XTypes 1.2 is in the eProsima's roadmap.
I can see in the roadmap.md that DDS-XTypes could be implemented till the end of the year. Could you please provide some information about the state of DDS-XTypes 1.2 implementation?
Thank you.

**Comment by einarhauks** [comment]
I'm interested in this as well. Any updates on the DDS-XTypes 1.2 support?

**Comment by ryanstowell** [comment]
I'm also interested specifically in using optional with Fast-DDS. Is there a roadmap for these XTypes features?

**Comment by JLBuenoLopez-eProsima** [comment]
Latest Fast CDR version, v2.0.0, supports the complete XTypes v1.3 specification. Fast CDR implements both Extended CDR Representation encodings, version 1 and 2, defined in the Data Representation section, 7.4, of the specification.
