### ISSUE TITLE
1.0.16 didn't increment version number?

### ISSUE THREAD

**Issue by wolfv** [eProsima/Fast-CDR#86]
Hi, I am maintaining Fast-CDR and Fast-RTPS on conda-forge (a cross-platform distribution for Windows, Linux and OSX): 

- https://github.com/conda-forge/fast-cdr-feedstock/
- https://github.com/conda-forge/fast-rtps-feedstock

We have builds for Linux, OS X and Win for Fast-CDR (and for Linux & Win for Fast-RTPS).

I noticed that the latest fast-cdr release does not increment the version number in configure.ac? Is that intentional?

If anyone of you maintainers wants to become a co-maintainer on the feedstocks, please let me know and I will be happy to give you maintainer rights on them!

**Comment by MiguelCompany** [comment]
> Hi, I am maintaining Fast-CDR and Fast-RTPS on conda-forge (a cross-platform distribution for Windows, Linux and OSX):
> 
> * https://github.com/conda-forge/fast-cdr-feedstock
> * https://github.com/conda-forge/fast-rtps-feedstock

WoW! Cool!

> We have builds for Linux, OS X and Win for Fast-CDR (and for Linux & Win for Fast-RTPS).

Why don't you have a OS X build for Fast-DDS ?

> I noticed that the latest fast-cdr release does not increment the version number in configure.ac? Is that intentional?

No, it was not intentional. Nevertheless, we're going to release 1.0.17 soon, so I think we will skip the change for 1.0.16.

> If anyone of you maintainers wants to become a co-maintainer on the feedstocks, please let me know and I will be happy to give you maintainer rights on them!

Sure! Could you add @EduPonz and @MiguelCompany (me) ? Thanks!

**Comment by MiguelCompany** [comment]
@wolfv Just released v1.0.17 (this time with the correct configure.ac)

**Comment by wolfv** [comment]
Hi @MiguelCompany that's awesome. When the bot opens the PR to the feedstock I will add you two as maintainers. 

I need to check what the OS X issue was with fast-rtps... Together we can probably figure it out and have an OS X build! That would be awesome.

**Comment by wolfv** [comment]
I am also kicking off an OS X build over here for Fast-RTPS: https://github.com/conda-forge/fast-rtps-feedstock/pull/7 let's see if that works.

**Comment by wolfv** [comment]
We have a working fast-dds build on Win, Linux and OS X now in staged recipes. 

Once you two confirm to be maintainers, I can merge and we have the binaries on conda-forge. https://github.com/conda-forge/staged-recipes/pull/13398

**Comment by MiguelCompany** [comment]
@wolfv I think this one can be closed.

**Comment by wolfv** [comment]
yes, new release works fine! https://github.com/conda-forge/fast-cdr-feedstock/pull/8
